package it.studiofontanelli.omniazero.integration.dto;
// Generated 28-nov-2016 12.05.19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AbiConfToken generated by hbm2java
 */
@Entity
@Table(name = "_abi_conf_token", schema = "public")
public class AbiConfToken implements java.io.Serializable {

	private int id;
	private String token;
	private Date insertDate;
	private Date updateDate;
	private boolean flAttivo;

	public AbiConfToken() {
	}

	public AbiConfToken(int id, String token, Date insertDate, boolean flAttivo) {
		this.id = id;
		this.token = token;
		this.insertDate = insertDate;
		this.flAttivo = flAttivo;
	}

	public AbiConfToken(int id, String token, Date insertDate, Date updateDate, boolean flAttivo) {
		this.id = id;
		this.token = token;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
		this.flAttivo = flAttivo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "token", nullable = false, length = 50)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "insert_date", nullable = false, length = 13)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", length = 13)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "fl_attivo", nullable = false)
	public boolean isFlAttivo() {
		return this.flAttivo;
	}

	public void setFlAttivo(boolean flAttivo) {
		this.flAttivo = flAttivo;
	}

}
