package it.studiofontanelli.omniazero.integration.dto;
// Generated 28-nov-2016 12.06.40 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AbiLkUsersClass generated by hbm2java
 */
@Entity
@Table(name = "_abi_lk_users_class")
public class AbiLkUsersClass implements java.io.Serializable {

	private int id;
	private String codice;
	private String descrizione;
	private Set<AbiMainUsers> abiMainUserses = new HashSet<AbiMainUsers>(0);

	public AbiLkUsersClass() {
	}

	public AbiLkUsersClass(int id, String codice, String descrizione) {
		this.id = id;
		this.codice = codice;
		this.descrizione = descrizione;
	}

	public AbiLkUsersClass(int id, String codice, String descrizione, Set<AbiMainUsers> abiMainUserses) {
		this.id = id;
		this.codice = codice;
		this.descrizione = descrizione;
		this.abiMainUserses = abiMainUserses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "codice", nullable = false, length = 3)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "descrizione", nullable = false, length = 20)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abiLkUsersClass")
	public Set<AbiMainUsers> getAbiMainUserses() {
		return this.abiMainUserses;
	}

	public void setAbiMainUserses(Set<AbiMainUsers> abiMainUserses) {
		this.abiMainUserses = abiMainUserses;
	}
	
}
