package it.studiofontanelli.omniazero.integration.dto;
// Generated 28-nov-2016 12.05.19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AbiMainUsersSession generated by hbm2java
 */
@Entity
@Table(name = "_abi_main_users_session")
public class AbiMainUsersSession implements java.io.Serializable {

	private int id;
	private AbiMainUsers abiMainUsers;
	private Date prevAccess;
	private String idSession;
	private String ip;
	private Boolean flAttiva;
	private Date dataFineSessione;

	public AbiMainUsersSession() {
	}

	public AbiMainUsersSession(int id, AbiMainUsers abiMainUsers, Date prevAccess) {
		this.id = id;
		this.abiMainUsers = abiMainUsers;
		this.prevAccess = prevAccess;
	}

	public AbiMainUsersSession(int id, AbiMainUsers abiMainUsers, Date prevAccess, String idSession, String ip,
			Boolean flAttiva, Date dataFineSessione) {
		this.id = id;
		this.abiMainUsers = abiMainUsers;
		this.prevAccess = prevAccess;
		this.idSession = idSession;
		this.ip = ip;
		this.flAttiva = flAttiva;
		this.dataFineSessione = dataFineSessione;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_abi_main_users", nullable = false)
	public AbiMainUsers getAbiMainUsers() {
		return this.abiMainUsers;
	}

	public void setAbiMainUsers(AbiMainUsers abiMainUsers) {
		this.abiMainUsers = abiMainUsers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prev_access", nullable = false, length = 29)
	public Date getPrevAccess() {
		return this.prevAccess;
	}

	public void setPrevAccess(Date prevAccess) {
		this.prevAccess = prevAccess;
	}

	@Column(name = "id_session", length = 32)
	public String getIdSession() {
		return this.idSession;
	}

	public void setIdSession(String idSession) {
		this.idSession = idSession;
	}

	@Column(name = "ip", length = 15)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "fl_attiva")
	public Boolean getFlAttiva() {
		return this.flAttiva;
	}

	public void setFlAttiva(Boolean flAttiva) {
		this.flAttiva = flAttiva;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fine_sessione", length = 29)
	public Date getDataFineSessione() {
		return this.dataFineSessione;
	}

	public void setDataFineSessione(Date dataFineSessione) {
		this.dataFineSessione = dataFineSessione;
	}

}
